### ISSUE TITLE
Possibility to add skype alpha

### ISSUE THREAD

**Issue by fliespl** [softasap/sa-communication-tools#2]
Since there is finally linux version of new client it would be great to add option to install it using this playbook.

https://community.skype.com/t5/Linux/What-s-New-in-Skype-1-2-for-Linux-Alpha/td-p/4440001

**Comment by Voronenko** [comment]
@fliespl   I have taken a look on Alpha  - unfortunately at it's present state it is identical to  
https://web.skype.com  ,  but wrapped into deb with electron framework.

No video sharing in groups ...   Very poor at that moment.

If you like - implement and submit pull request back - I will review & merge it into playbook.

**Comment by Voronenko** [comment]
Introduced in 1.1.0
